# Generated by Django 3.0.8 on 2020-07-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('catogery', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('post_body', models.TextField()),
                ('date_pub', models.DateField()),
            ],
        ),
    ]
