# Generated by Django 3.0.8 on 2020-07-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_add_blog_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_blog',
            name='post_img',
        ),
    ]
